server:
  port: 8889

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      routes:
#        - id: identity_service
#          uri: http://localhost:8080
#          predicates:
#          - Path=${app.api-prefix}/identity/**
#          filters:
#          - StripPrefix=2
#        - id: profile_service
#          uri: http://localhost:8081
#          predicates:
#          - Path=${app.api-prefix}/profile/users/**
#          filters:
#          - StripPrefix=2
      routes:

        - id: identity_service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2

        # ------------------------------------------

        - id: service-fixphone
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/phonefix/getFixPhone/{id}
            - Method=GET

              #
              #          filters:
            #            - name: AuthFilter
            # staff staffstaffstaffstaffstaffstaffstaffstaffstaffstaffstaffstaffstaffstaffstaffstaff

        # ------------------------------------------

        - id: service-fixphone
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/phonefix/getAllFixPhone
            - Method=GET


            # ------------------------------------------

        # staff staffstaffstaffstaffstaffstaffstaffstaffstaffstaffstaffstaffstaffstaffstaffstaff
        - id: service-fixphone
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/phonefix
            - Method=POST

        #          filters:
        #          - name: AuthFilter
        # ------------------------------------------

        # admin adminadminadminadminadminadminadminadminadminadminadminadminadminadminadminadmin
        - id: service-phones
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/phone/addPhone
            - Method=POST

#          filters:
#            - name: AuthFilter
        # ------------------------------------------
        - id: service-phones
          uri: http://localhost:9006
          predicates:
             - Path=/api/v1/getDetailCustomer/**
             - Method=GET
        # ------------------------------------------

        # ------------------------------------------
        - id: servive-customer
          uri: http://localhost:9006
          predicates:
             - Path=${app.api-prefix}/customer/getDetailCustomer/**
             - Method=GET
         # ------------------------------------------



    default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
    globalcors:
      corsConfigurations:
        '[/**]':
          allowedOrigins: "*"
          allowedMethods: "*"
          allowedHeaders: "*"

      eureka:
        client:
          service-url:
            defaultZone: http://localhost:8762/eureka/
          register-with-eureka: true
          fetch-registry: true

